<?php

declare(strict_types=1);

namespace Nkamuo\NotificationTrackerBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('notification_tracker');
        
        $treeBuilder->getRootNode()
            ->children()
                ->booleanNode('enabled')
                    ->defaultTrue()
                ->end()
                
                ->arrayNode('tracking')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('track_opens')->defaultTrue()->end()
                        ->booleanNode('track_clicks')->defaultTrue()->end()
                        ->booleanNode('store_content')->defaultTrue()->end()
                        ->integerNode('content_retention_days')->defaultValue(90)->end()
                        ->booleanNode('use_async')->defaultTrue()->end()
                    ->end()
                ->end()
                
                ->arrayNode('storage')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('attachment_directory')
                            ->defaultValue('%kernel.project_dir%/var/notification-tracker/attachments')
                        ->end()
                        ->scalarNode('template_directory')
                            ->defaultValue('%kernel.project_dir%/var/notification-tracker/templates')
                        ->end()
                        ->integerNode('max_attachment_size')
                            ->defaultValue(10485760)
                        ->end()
                        ->arrayNode('allowed_mime_types')
                            ->scalarPrototype()->end()
                            ->defaultValue(['application/pdf', 'image/jpeg', 'image/png'])
                        ->end()
                    ->end()
                ->end()
                
                ->arrayNode('retry')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('max_retries')->defaultValue(3)->end()
                        ->integerNode('retry_delay')->defaultValue(3600)->end()
                        ->floatNode('retry_multiplier')->defaultValue(2.0)->end()
                        ->integerNode('max_retry_delay')->defaultValue(86400)->end()
                    ->end()
                ->end()
                
                ->arrayNode('webhooks')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('async_processing')->defaultTrue()->end()
                        ->booleanNode('verify_signatures')->defaultTrue()->end()
                        ->booleanNode('ip_whitelist_enabled')->defaultFalse()->end()
                        ->arrayNode('providers')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('secret')->end()
                                    ->scalarNode('signing_key')->end()
                                    ->scalarNode('auth_token')->end()
                                    ->arrayNode('ip_whitelist')
                                        ->scalarPrototype()->end()
                                    ->end()
                                    ->arrayNode('events')
                                        ->scalarPrototype()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                
                ->arrayNode('channels')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('email')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                                ->booleanNode('track_opens')->defaultTrue()->end()
                                ->booleanNode('track_clicks')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->arrayNode('sms')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->arrayNode('slack')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->arrayNode('telegram')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                            ->end()
                        ->end()
                        ->arrayNode('push')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')->defaultTrue()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                
                ->arrayNode('templates')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->scalarNode('default_locale')->defaultValue('en')->end()
                        ->booleanNode('cache_enabled')->defaultTrue()->end()
                        ->integerNode('cache_ttl')->defaultValue(3600)->end()
                    ->end()
                ->end()
                
                ->arrayNode('api')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('docs_enabled')->defaultTrue()->end()
                        ->scalarNode('docs_path')->defaultValue('/api/docs')->end()
                        ->arrayNode('pagination')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('items_per_page')->defaultValue(30)->end()
                                ->integerNode('maximum_items_per_page')->defaultValue(100)->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                
                ->arrayNode('analytics')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->booleanNode('real_time')->defaultTrue()->end()
                        ->integerNode('retention_days')->defaultValue(365)->end()
                        ->booleanNode('aggregate_data')->defaultTrue()->end()
                    ->end()
                ->end()
                
                ->arrayNode('messenger')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('transport')->defaultValue('async')->end()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->integerNode('retry_strategy_max_retries')->defaultValue(3)->end()
                        ->integerNode('retry_strategy_delay')->defaultValue(1000)->end()
                    ->end()
                ->end()
                
                // ... rest of configuration
            ->end();
        
        return $treeBuilder;
    }
}