monolog:
    channels:
        - notification_tracker
        - notification_tracker_mailer
        - notification_tracker_notifier
        - notification_tracker_webhook
        - notification_tracker_retry
        - notification_tracker_messenger