services:
    Nkamuo\NotificationTrackerBundle\Controller\Api\RetryMessageController:
        tags: ['controller.service_arguments']

    Nkamuo\NotificationTrackerBundle\Controller\Api\CancelMessageController:
        tags: ['controller.service_arguments']

    Nkamuo\NotificationTrackerBundle\Controller\Api\SendNotificationController:
        tags: ['controller.service_arguments']

    Nkamuo\NotificationTrackerBundle\Controller\Api\ScheduleNotificationController:
        tags: ['controller.service_arguments']

    # Note: State processors and providers removed as they don't exist yet
    # Uncomment when implemented:
    # Nkamuo\NotificationTrackerBundle\State\MessageStateProcessor:
    #     tags:
    #         - { name: 'api_platform.state_processor' }

    # Nkamuo\NotificationTrackerBundle\State\MessageStateProvider:
    #     tags:
    #         - { name: 'api_platform.state_provider' }