services:
    Nkamuo\NotificationTrackerBundle\Command\ProcessFailedMessagesCommand:
        tags:
            - { name: console.command }

    Nkamuo\NotificationTrackerBundle\Command\MessageAnalyticsCommand:
        tags:
            - { name: console.command }

    Nkamuo\NotificationTrackerBundle\Command\CleanupOldMessagesCommand:
        tags:
            - { name: console.command }

    Nkamuo\NotificationTrackerBundle\Command\ExportMessagesCommand:
        tags:
            - { name: console.command }