services:
    # Event Subscribers - Only include existing classes
    Nkamuo\NotificationTrackerBundle\EventSubscriber\MailerEventSubscriber:
        arguments:
            $enabled: '%notification_tracker.tracking.enabled%'
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: notification_tracker_mailer }

    # Additional event subscribers commented out until implemented:
    # Nkamuo\NotificationTrackerBundle\EventSubscriber\NotifierEventSubscriber:
    #     arguments:
    #         $logger: '@monolog.logger.notification_tracker.notifier'
    #         $enabled: '%notification_tracker.tracking.enabled%'
    #     tags:
    #         - { name: kernel.event_subscriber }

    # Nkamuo\NotificationTrackerBundle\EventSubscriber\MessengerEventSubscriber:
    #     arguments:
    #         $logger: '@monolog.logger.notification_tracker.messenger'
    #     tags:
    #         - { name: kernel.event_subscriber }