services:
    # Message Handlers - Use AsMessageHandler attribute for auto-configuration
    Nkamuo\NotificationTrackerBundle\MessageHandler\TrackEmailMessageHandler:
        arguments:
            $logger: '@monolog.logger.notification_tracker'

    Nkamuo\NotificationTrackerBundle\MessageHandler\ProcessWebhookMessageHandler:
        arguments:
            $logger: '@monolog.logger.notification_tracker.webhook'

    Nkamuo\NotificationTrackerBundle\MessageHandler\RetryFailedMessageHandler:
        arguments:
            $logger: '@monolog.logger.notification_tracker.retry'