services:
    # Message Handlers - Use AsMessageHandler attribute for auto-configuration
    Nkamuo\NotificationTrackerBundle\MessageHandler\TrackEmailMessageHandler:
        tags:
            - { name: monolog.logger, channel: notification_tracker }

    Nkamuo\NotificationTrackerBundle\MessageHandler\ProcessWebhookMessageHandler:
        tags:
            - { name: monolog.logger, channel: notification_tracker_webhook }

    Nkamuo\NotificationTrackerBundle\MessageHandler\RetryFailedMessageHandler:
        tags:
            - { name: monolog.logger, channel: notification_tracker_retry }