imports:
    - { resource: transport.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Nkamuo\NotificationTrackerBundle\:
        resource: '../../*'
        exclude:
            - '../../{DependencyInjection,Entity,Resources,Tests,Migration}'
            - '../../NotificationTrackerBundle.php'

    # Core Services with proper logger configuration
    Nkamuo\NotificationTrackerBundle\Service\MessageTracker:
        tags:
            - { name: monolog.logger, channel: notification_tracker }

    # Messenger Middleware for notification tracking stamps
    Nkamuo\NotificationTrackerBundle\Messenger\Middleware\NotificationTrackingMiddleware:
        tags:
            - { name: messenger.middleware, priority: 100 }
            - { name: monolog.logger, channel: notification_tracker_middleware }

    # Remove repository services - they're auto-configured by Doctrine
    # Just ensure they're tagged properly in the Entity annotations