services:
    _defaults:
        autowire: true
        autoconfigure: true

    Nkamuo\NotificationTrackerBundle\:
        resource: '../../*'
        exclude:
            - '../../{DependencyInjection,Entity,Resources,Tests}'
            - '../../NotificationTrackerBundle.php'

    # Core Services
    Nkamuo\NotificationTrackerBundle\Service\MessageTracker:
        arguments:
            $logger: '@monolog.logger.notification_tracker'

    # Remove repository services - they're auto-configured by Doctrine
    # Just ensure they're tagged properly in the Entity annotations