imports:
    - { resource: transport.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Nkamuo\NotificationTrackerBundle\:
        resource: '../../*'
        exclude:
            - '../../{DependencyInjection,Entity,Resources,Tests,Migration}'
            - '../../NotificationTrackerBundle.php'

    # Core Services with proper logger configuration
    Nkamuo\NotificationTrackerBundle\Service\MessageTracker:
        arguments:
            $storeContent: true
        tags:
            # - { name: monolog.logger, channel: notification_tracker }

    # NotificationTracker service for handling notifications
    Nkamuo\NotificationTrackerBundle\Service\NotificationTracker:
        tags:
            # - { name: monolog.logger, channel: notification_tracker }

    # AttachmentManager with required parameters
    Nkamuo\NotificationTrackerBundle\Service\AttachmentManager:
        arguments:
            $attachmentDirectory: '%kernel.project_dir%/var/attachments'
            $maxSize: 10485760  # 10MB
            $allowedMimeTypes: ['image/jpeg', 'image/png', 'application/pdf', 'text/plain']

    # Messenger Middleware for notification tracking stamps
    Nkamuo\NotificationTrackerBundle\Messenger\Middleware\NotificationTrackingMiddleware:
        tags:
            - { name: messenger.middleware, priority: 100 }
            # - { name: monolog.logger, channel: notification_tracker_middleware }

    # Webhook Provider Registry
    Nkamuo\NotificationTrackerBundle\Service\WebhookProviderRegistry:
        arguments: []

    # WebhookProcessor with explicit configuration (no logger tag to avoid circular deps)
    Nkamuo\NotificationTrackerBundle\Service\WebhookProcessor:
        arguments:
            $asyncProcessing: true
            $verifySignatures: true

    # Webhook Providers (with optional secrets)
    Nkamuo\NotificationTrackerBundle\Webhook\Provider\SendGridWebhookProvider:
        arguments:
            $secret: ''
        tags:
            - { name: notification_tracker.webhook_provider }

    Nkamuo\NotificationTrackerBundle\Webhook\Provider\MailgunWebhookProvider:
        arguments:
            $secret: ''
        tags:
            - { name: notification_tracker.webhook_provider }

    # Remove repository services - they're auto-configured by Doctrine
    # Just ensure they're tagged properly in the Entity annotations