services:
    # Core Tracking Services - Main definitions moved to services.yaml to avoid duplicates

    Nkamuo\NotificationTrackerBundle\Service\MessageRetryService:
        arguments:
            $messageBus: '@messenger.bus.default'
            $entityManager: '@doctrine.orm.entity_manager'
            $messageTracker: '@Nkamuo\NotificationTrackerBundle\Service\MessageTracker'
        tags:
            - { name: monolog.logger, channel: notification_tracker }

    # WebhookProcessor moved to services.yaml to avoid duplicates

    Nkamuo\NotificationTrackerBundle\State\NotificationCreateProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: monolog.logger, channel: notification_tracker }
