services:
    # Webhook Providers (only include implemented classes)
    Nkamuo\NotificationTrackerBundle\Webhook\Provider\SendGridWebhookProvider:
        arguments:
            $secret: '%env(SENDGRID_WEBHOOK_SECRET)%'
        tags:
            - { name: 'notification_tracker.webhook_provider', provider: 'sendgrid' }

    # TODO: Implement additional webhook providers
    # Nkamuo\NotificationTrackerBundle\Webhook\Provider\TwilioWebhookProvider:
    #     arguments:
    #         $authToken: '%env(TWILIO_AUTH_TOKEN)%'
    #     tags:
    #         - { name: 'notification_tracker.webhook_provider', provider: 'twilio' }

    Nkamuo\NotificationTrackerBundle\Webhook\Provider\MailgunWebhookProvider:
        arguments:
            $secret: ''
        tags:
            - { name: 'notification_tracker.webhook_provider', provider: 'mailgun' }

    # Nkamuo\NotificationTrackerBundle\Webhook\Provider\MailchimpWebhookProvider:
    #     arguments:
    #         $secret: '%env(MAILCHIMP_WEBHOOK_SECRET)%'
    #     tags:
    #         - { name: 'notification_tracker.webhook_provider', provider: 'mailchimp' }